### ISSUE TITLE
CORE-RT: CI for Core

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/core-runtime#34]
## CI for Core Design :

The design suggested that the approach is for Core-RT to apply it from top to bottom.

An example of this is:

- Every module has its own protobuf data, its own table in the database, or its own `data-plane` so isolation is in effect. 

- The makefiles in each module then behave as the source of truth for each of them. Where it controls the build, tests, and reaching down to each external dependencies (`tools`). 

- The 2 points above will be the defining theme for even the dependencies, so any `tool` needed will have the same design as the two points above. 

- The CI job then is to exactly does the same thing, only for every defined modules and tools. That's what it meant for makefiles to drive the CI.  

- So the builds and the tests are reproducible both in CI / remotes or in local dev setup. Because it's essentially the same.

- The other repos will do the exact same thing, for example `packages` will use core-bs and core-fish that packages will be publishing binaries, expecting others to get them using core-fish. It's consistent throughout. 

So the CI needs to do matrix of these:

- `build-all` which is to build, tests, and get dependencies of each modules. 
- `build-cross` which is to build and release for all supported architectures / platforms.

### Core-BS & Core-Fish part

`multibuild.go` job is to make reflection out of the tagged releases and generate `core-fish` food recipes from it. 

- How does it work?

`multibuild` will be driven by a textual config containing repo name and repo url, it will then find tagged releases of each repository.

This way, only way to modify `core-fish` repo is via `multibuild`

- How does it generate `fish foods` from the releases?

 Via reflection, given the name of the tarballs / compressed assets, in the format of `$(ASSET_NAME)-$(OS)-$(ISA)`, it will create fish food recipe for each OS and ISA / architecture. 

On install, the binary / compressed asset will be decompressed, and renamed to `$(ASSET_NAME)` then installed to the agreed global PATH.

- Where would it be located and why?

`core-fish` repo will be the location for user defined config, multibuild will parse that config and do the steps explained above.
 
`core-bs` repo will be the ideal location for multibuild binary. `multibuild.go` will have the default configuration defined there also so that when user defined config does not exist in the `core-fish` it will revert back to the default one.

### Suggestions from @winwisely99

https://github.com/exaring/release-cli
suggest using this for release management

---

https://github.com/apache/arrow/blob/master/.github/workflows/go.yml
suggests using this approach that is similar to use
- they use .sh instead of makefile but does not matter
- but some good tip in here

Add this:
like here:https://github.com/pingcap-incubator/tiup-cluster/blob/master/.github/workflows/integrate.yaml

SO then we can run the same code locally as we do in CI. this will make CI much easier to manage but also to allow us to move off github which we need to do.

--- 
Also flutter to use cache will be way faster

https://github.com/GetStream/stream-chat-dart/blob/master/.github/workflows/main.ym

**Comment by WinWisely268** [comment]
Notes from chat:

## Makefiles

- Get the CI working via local make files first, logic is encapsulated in make targets so all the things are working the right way first.

- Makefiles does git tagging (gitr-tag) and then reflects on the tagging basically.

## Integration

- Get the whole thing from top to bottom work correctly not just one part of the repo so nothing is missed.

The specified makefiles build, esp. `build-all` part is designed to be used to build from the top, i.e. the examples, reach down to the make files below (i.e. the tool it needed and or external dependencies, all managed by makefiles) and build things that is needed by it. 


## Suggested way of doing it from the chat:

- `build-all` can be used to build cross OS architectures

- `dep` is generally for getting dependencies, binary.

**Comment by joe-getcouragenow** [comment]
https://github.com/exaring/release-cli
suggest using this for release management

---

https://github.com/apache/arrow/blob/master/.github/workflows/go.yml
suggest usin this approach that is simialr to use
- they use .sh instead of makefile but does not matter
- but some good tip in here

**Comment by winwisely99** [comment]
Ad this:
like here:https://github.com/pingcap-incubator/tiup-cluster/blob/master/.github/workflows/integrate.yaml

SO then we can run the same code locally as we do in CI. this will make CI much easier to manage but also to allow us to move off github which we need to do.

--- 
Also flutter to use cache will be way faster

https://github.com/GetStream/stream-chat-dart/blob/master/.github/workflows/main.ym
